### ISSUE TITLE
Can you add a button on the dropdown menu that stops everything from happening? I.e. stop recording, playback, etc.

### ISSUE THREAD

**Issue by ajalmaguer** [mahhov/extbsv-extension-better-service-virtualization#1]

**Comment by mahhov** [comment]
sure can.
on a side note, have u encountered an issue where it's adversarial impacted some site when in record mode?

**Comment by ajalmaguer** [comment]
haven't noticed it affecting another site. main thing is I wasn't sure what it was doing sometimes. Was it recording? Was it not recording? Is it playing back anything? Or is it doing nothing? After recording and playing back successfully, I wanted to stop it from doing anything but couldn't figure out how to do that. I ended up disabling the extension to make sure it wasn't running.

on a side note: i added this to the config file to an error from showing up on pages where angular wasn't defined.
```js
if(typeof angular !== 'undefined') {
// ...config code here
}
```

**Comment by mahhov** [comment]
the top of the popup should say either "recording" or "currently replaying $recordingName" to indicate what it's doing. 

When it's recording, it shouldn't affect any websites' behavior, hence y i was asking if u'd noticed it affecting a website, then that may indicate a bug that needs to be looked into.

regardless, i'll add an option to stop both recording and replaying.

**Comment by mahhov** [comment]
should be resolved now in current version.
- made the headers stand out more in order to clarify when it's recording and when replaying.
- there's a disable/enable button at the bottom of the popup ui. it'll be very clear when disabled, as all the other ui disappears except the enable button.
